var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                       o          x   x         ",
   "                                                     xxx    xxx   x!x!x         ",
   "                                     o o      y   xxx             x!!!x         ",
   "                                             xxx                  xx!xx         ",
   "                                  xxxxxf                          xxxxx      h  ",
   "  h                                        h                                xx  ",
   "  xx                                      o o                                x  ",
   "  x                      o                                          o         x ",
   "  x                                      xxxxx                   o          o x ",
   "  x                 o xxxx               x   x               xxxx   o           ",
   "  x  @              g x  x               x   x                    xxxxx         ",
   "  xxxxxxxxxxx  xxxxxxxx  xxxxxxx     xxxxxxxxxxxxxxxxxxx     xxxx   xxxxxxxxx   ",
   "            x  x                x   x                  x     x                  ",
   "            x!!x                x!!!x                  x!!!!!x                  ",
   "            xxxx                x!!!x                  x!!!!!x                  ",
   "                                xxxxx                  xxxxxxx                  ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x    y                xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x         o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                  d          xx  |   |   |  xx         xxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                             xxx     xxx          xxxxxxx        xxx         xxx                  ",
   "                                               x    xx                           x x         x x                  ",
   "                                               x     x                             x      xxx x                   ",
   "                                               xo    x                             x         x                    ",
   "                                               xx    x                             xxx       x                    ",
   "                                      b        x     x      o  o     x   x         x         x                    ",
   "                xxxxx        xxxx o xxxx       x     x               x   x         x         x                    ",
   "             xxx  h  xxx        x   x          x     x     xxxxxx    x   x   xxxxxxxxxx      x                    ",
   "           xxxx       xxxx      x o x          x    xx               x   x   x               x                    ",
   "     @      g  g  g  g          x   x          x     x               x   x   x            xxxx                    ",
   "    xxx    xxxxxxxxxxxxxxxx     x o x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x      xxxx                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx   o   xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx   o   xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx            b                                                       ",
   "                                       x x       xx   xx   !!!        !!!  xxx                                ",
   "                                       x x        x   x    !x!        !x!                                     ",
   "                                     xxxx xxx     x   x     x          x                                      ",
   "                                      x   x       x   x     x   oooo   x       xxx                            ",
   "                                      x   x       x   x                x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                    xxx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                    xxx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                   xxxx   xxx         x                     x g x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           xx     xxxx                      x g x                  ",
   "                             xxx  xx xxx xxx     o o  x!!!!!!!!!!!!!!x                  xvx                   ",
   "                             x     x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xxx          xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                                                          x  ",
   "  x                           x           x                                                                x  ",
   "  x                           xx          x                                                                x  ",
   "  x                                                xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                      xxx       o o                                   x         xxx                     x  ",
   "  x                    xxxxx  xx          x                             xxx       x!!!x          x         x  ",
   "  x                  oxxx     x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxxxxx     xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @        xxxx        x           x!!x    x!!!!x    x!!!!x    xx   xx            o       x      o  x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                    h x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                                  xxx x       ",
   "                   xxx                                                                                x       ",
   "       !     !      d                                        y    y   yy  y   y   y         y   y  y     y    ",
   "       x     x                                                y   y  y  y y   y    y       y    y  y y   y    ",
   "       x     x            x                                    y y   y  y y   y     y     y     y  y  y  y    ",
   "       x=    x                                                  y    y  y y   y     y  y  y     y  y   y y    ",
   "       !  o               o                                     y     yy   yyy       y   y      y  y     y    ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                  b                                                                                           ",
   "               xxxxxx     o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxxx        xxx         xxx                                 x                  x                 ",
   "             x                                                   d                                            ",
   "   f         x      xxx                                          ||                                           ",
   "  xxxxxxxxxxx                    g                                                                            ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xxxxxxxxxxxxxxx                d                               x      ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   xxxxxx                 xxx                                  ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
